// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.claylin.grpc.proto.service;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\014entity.proto2H\n\010Uservice\022\027" +
      "\n\003add\022\005.User\032\007.RetMsg\"\000\022#\n\010getByUid\022\014.Ge" +
      "tByUidReq\032\007.RetMsg\"\000B-\n\036com.claylin.grpc" +
      ".proto.serviceB\tUserProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.claylin.grpc.proto.entity.UserEntityProto.getDescriptor(),
        }, assigner);
    com.claylin.grpc.proto.entity.UserEntityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
