// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.claylin.grpc.proto.entity;

public interface GetByUidReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetByUidReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   */
  long getUid();
}
