// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.claylin.grpc.proto.entity;

public interface RetMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RetMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>.google.protobuf.Any data = 2;</code>
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 2;</code>
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
