// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.claylin.grpc.proto.entity;

public final class UserEntityProto {
  private UserEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetByUidReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetByUidReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RetMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RetMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014entity.proto\032\031google/protobuf/any.prot" +
      "o\".\n\004User\022\013\n\003uid\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\013\n\003" +
      "age\030\003 \001(\005\"\032\n\013GetByUidReq\022\013\n\003uid\030\001 \001(\003\":\n" +
      "\006RetMsg\022\014\n\004code\030\001 \001(\005\022\"\n\004data\030\002 \001(\0132\024.go" +
      "ogle.protobuf.AnyB2\n\035com.claylin.grpc.pr" +
      "oto.entityB\017UserEntityProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Uid", "Name", "Age", });
    internal_static_GetByUidReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetByUidReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetByUidReq_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_RetMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RetMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RetMsg_descriptor,
        new java.lang.String[] { "Code", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
